apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: ipannounce
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  interfaces:
  - ens18
  - eth0
  externalIPs: true
  loadBalancerIPs: true

---

apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ippool"
spec:
  blocks:
  - cidr: "192.168.50.10/32"