# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/VALUES.md

providers:
  kubernetesGateway:
    enabled: true
    # experimentalChannel: true
  
  kubernetesIngress:
    enabled: false

#
# So ports: maps to entrypoints on the regular Traefik configuration. The exposedPort and expose.external settings are required to make the Minecraft port work with the Traefik IngressRouteTCP configuration. 
#
# https://doc.traefik.io/traefik/reference/install-configuration/entrypoints/
ports:
  web:
    port: 80
  websecure:
    port: 443
    transport:
      # Immich large uploads require timeouts to 600s
      respondingTimeouts:
        writeTimeout: 1200s
        readTimeout: 1200s

  # https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#deploy-multiple-gateways-with-a-single-traefik-deploymentdaemonset
  minecraft:
    port: 25565
    exposedPort: 25565
    expose:
      default: true
    protocol: TCP

# if we wanted Traefik to maintain the gateway.yaml file, we could do it here.
gateway:
  enabled: false

gatewayClass:
  enabled: true
  name: traefik

# Optional: Enable logs and metrics
# logs:
#   general:
#     level: INFO

#   access:
#     enabled: true
#     format: json  # or "common" for CLF format
#     # filters:
#     #   statusCodes:
#     #     - "200"
#     #     - "400-404"
#     #     - "500-503"
#     fields:
#       general:
#         defaultMode: keep
#         # names:
#         #   ClientUsername: drop
#       headers:
#         defaultMode: keep
#         names:
#           # User-Agent: redact
#           Content-Type: keep

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"