---
- name: Configure all K3s nodes
  hosts: all
  become: true
  tasks:
    # - name: Disable FirewallD
    #   ansible.builtin.systemd:
    #     name: firewalld
    #     enabled: false
    #     state: stopped

    - name: Set disable_ipv6 parameters in the sysctl configuration file
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        reload: false
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6

    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: latest
        update_cache: true

    - name: Start qemu-guest-agent
      ansible.builtin.systemd:
        name: qemu-guest-agent
        enabled: true
        state: started

    # - name: Install iscsi utilities
    #   ansible.builtin.yum:
    #     name: iscsi-initiator-utils
    #     state: latest

    # - name: Enable iscsid.service
    #   ansible.builtin.systemd:
    #     name: iscsid.service
    #     enabled: true
    #     state: started

    # - name: Enable iscsid.socket  
    #   ansible.builtin.systemd:
    #     name: iscsid.socket
    #     enabled: true


    - name: Update everything in APT
      ansible.builtin.apt:
        name: '*'
        state: latest
