registry: "gcr.io/datadoghq"
datadog:
  apiKeyExistingSecret: "datadog-secret"
  site: "us5.datadoghq.com"
  logs:
    enabled: true
    containerCollectAll: true

providers:
  talos:
    enabled: true