registry: "gcr.io/datadoghq"
datadog:
  apiKeyExistingSecret: "datadog-secret"
  site: "us5.datadoghq.com"
  clusterName: talos-k8s

  kubelet:
    tlsVerify: false

  logs:
    enabled: true
    containerCollectAll: true

  processAgent:
      enabled: true
      processCollection: true

  confd:
    # cilium.yaml: |-
    #   init_config:
    #   instances:
    #     - use_openmetrics: true
    #       agent_endpoint: http://localhost:9090/metrics
    cilium.yaml: null

agents:
  image:
    tag: 7.68.3
    env:
      - name: DD_TLS_VERIFY
        value: "false"

providers:
  talos:
    enabled: true