registry: "gcr.io/datadoghq"
datadog:
  apiKeyExistingSecret: "datadog-secret"
  site: "us5.datadoghq.com"
  clusterName: talos-k8s

  kubelet:
    tlsVerify: false

  logs:
    enabled: true
    containerCollectAll: true

  processAgent:
      enabled: true
      processCollection: true

providers:
  talos:
    enabled: true