prometheus:
  prometheusSpec:
    retention: 10d

#    replicas: 2
#    podAntiAffinity: "hard"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:

  ingress:
    enabled: true 
    hosts:
    - grafana.192.168.100.70.nip.io

alertmanager:

  ## Deploy alertmanager
  ##
  enabled: false

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false