prometheus:
  prometheusSpec:
    retention: 10d

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:

  ingress:
    enabled: true 
    hosts:
    - grafana.192.168.100.130.nip.io

alertmanager:
  enabled: false

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false