apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "my-django-chart.fullname" . }}-db
spec:
  instances: {{ .Values.db.instances | default 3 }}
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  
  storage:
    size: {{ .Values.db.storageSize | default "1Gi" }}
  
  bootstrap:
    initdb:
      database: {{ .Values.db.name | default "app" | quote }}
      owner: {{ .Values.db.user | default "app" | quote }}
