# https://docs.siderolabs.com/talos/v1.13/networking/configuration/aliases
apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
    match: true # as there is a single link only, we can match it this way