kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "database"
  labels:
    team: acid

  annotations:
      kubectl.kubernetes.io/last-applied-configuration: ""

spec:
  teamId: "acid"
  postgresql:
    version: "15"
  numberOfInstances: 1

  enableMasterLoadBalancer: false
  volume:
    size: "20Gi"

  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      cpu: 2500m
      memory: 3000Mi

  users:
    homedb: []

  databases:
    stockprices: homedb
    quotes: homedb

