kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "database"

  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "15"
  numberOfInstances: 2
  enableMasterLoadBalancer: true
  volume:
    size: "20Gi"

  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 2500m
      memory: 3000Mi

  users:
    django: []

  databases:
    piku: django
    play: django
    samplepiku: django
    sampledb: django
