kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "database"
  labels:
    team: acid
  namespace: postgres

  annotations:
      kubectl.kubernetes.io/last-applied-configuration: ""

spec:
  teamId: "acid"
  postgresql:
    version: "15"
  numberOfInstances: 1
  enableMasterLoadBalancer: true
  volume:
    size: "10Gi"

  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 2500m
      memory: 3000Mi

  users:
    homedb: []

  databases:
    stockprices: homedb
    quotes: homedb

