kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "utility"

  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "15"
  numberOfInstances: 3
  enableMasterLoadBalancer: true
  volume:
    size: "20Gi"
  users:
    user: []
  databases:
    django: user
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 2500m
      memory: 3000Mi