kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "django"
  labels:
    team: home

spec:
  teamId: "home"
  postgresql:
    version: "15"
  numberOfInstances: 3
  enableConnectionPooler: false
  enableMasterLoadBalancer: true
  volume:
    size: "10Gi"
    # storageClass: longhorn-single

  users:
    adminsyymgnc: []
    user: []
    
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 2000m
      memory: 1000Mi