kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "sotb-1"
  namespace: "default"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "15"
  numberOfInstances: 2
  enableConnectionPooler: true
  volume:
    size: "1Gi"
    storageClass: longhorn-single

  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 500Mi