apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ippool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.100.135/32

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2announce
  namespace: metallb-system
  