providers:
  kubernetesGateway:
    enabled: true
  kubernetesIngress:
    enabled: false             # Disable legacy Ingress provider
  # kubernetesCRD:
  #   enabled: false


# Helm Values for Traefik - See README for referench.
# Immich large uploads require timeouts to 0
# ports.websecure.transport.respondingTimeouts.readTimeout
# ports.websecure.transport.respondingTimeouts.writeTimeout
ports:
  web: 
    port: 80
  websecure:
    port: 443
    transport:
      respondingTimeouts:
        writeTimeout: 0
        readTimeout: 0

gateway:
  enabled: false

gatewayClass:
  enabled: true
  name: traefik

# Optional: Enable logs and metrics
logs:
  general:
    level: INFO

  access:
    enabled: true
    format: json  # or "common" for CLF format
    # filters:
    #   statusCodes:
    #     - "200"
    #     - "400-404"
    #     - "500-503"
    fields:
      general:
        defaultMode: keep
        # names:
        #   ClientUsername: drop
      headers:
        defaultMode: keep
        names:
          # User-Agent: redact
          Content-Type: keep

# metrics:
#   prometheus:
#     enabled: true

