datadog:
  site: "us5.datadoghq.com"
  apiKeyExistingSecret: "datadog-secret"
  apm:
    # portEnabled: true
    instrumentation:
      enabled: true
      
      targets:
        - name: "default-target"
          ddTraceVersions:
            python: "3"

  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true

  processAgent:
    enabled: true
    processCollection: true

  clusterName: talos-k8s

  operator:
    enabled: false

  kubelet:
    tlsVerify: false

  ignoreAutoConfig:
    - cilium

agents:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

# https://docs.datadoghq.com/containers/cluster_agent/admission_controller/?tab=helm#configuration
# clusterAgent:
#   admissionController:
#     enabled: true
#     mutateUnlabelled: false
  
#   replicas: 2
#   pdb:
#     create: true


providers:
  talos:
    enabled: true