datadog:
  apiKeyExistingSecret: "datadog-secret"
  appKeyExistingSecret: "datadog-secret" #
  site: "us5.datadoghq.com"
#
  kubelet:
    tlsVerify: false
    useApiServer: true
  clusterAgent:
    enabled: true
  clusterChecks:
    enabled: true
#
  # apm:
  #   instrumentation:
  #     enabled: true
  #     libVersions:
  #       dotnet: "3"
  #       js: "5"
  #       python: "3"
  logs:
    enabled: true
    containerCollectAll: true
  serviceMonitoring:
    enabled: true
  networkMonitoring:
    enabled: true
  processAgent:
    enabled: true
  orchestratorExplorer:
    enabled: true
#
agents:
  containers:
    agent:
      # resources for the Agent container
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 256Mi

    traceAgent:
      # resources for the Trace Agent container
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 200m
          memory: 256Mi

    processAgent:
      # resources for the Process Agent container
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 200m
          memory: 256Mi
          
  priorityClassCreate: true
#
clusterAgent:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
#
providers:
  # gke:
  #   autopilot: true
  talos:
    enabled: true
