ingress:
  enabled: true
  annotations: 
    cert-manager.io/cluster-issuer: clusterissuer

  hosts:
    - host: cd.k.3756home.org
      paths:
      - path: /
        backend:
          serviceName: chart-example.local
          servicePort: 5000
  tls:
   - secretName: changedetector
     hosts:
       - cd.k.3756home.org
