---
  - name: clone to new VM
    community.general.proxmox_kvm:
      api_user: root@pam
      api_password: got1proxmox
      api_host: 192.168.100.40
      clone: random
      vmid: '{{ cloneid }}'
      newid: '{{ targetid }}'
      name: '{{ hostname }}'
      node: prox1
      storage: ZFS-SSD
      format: qcow2
      timeout: 500
      ipconfig:
        ipconfig0: '{{ip}},gw=192.168.100.254'

  - name: Start VM
    community.general.proxmox_kvm:
      api_user: root@pam
      api_password: got1proxmox
      api_host: 192.168.100.40
      name: '{{ hostname }}'
      node: prox1
      state: started

  # - name: Pause 
  #   ansible.builtin.pause:
  #     minutes: 3

  - name: Set disable_ipv6 parameters in the sysctl configuration file
    ansible.posix.sysctl:
      name: "{{ item }}"
      value: "1"
      reload: false
    loop:
      - net.ipv6.conf.all.disable_ipv6
      - net.ipv6.conf.default.disable_ipv6
      - net.ipv6.conf.lo.disable_ipv6

  - name: Install qemu-guest-agent
    ansible.builtin.apt:
      name: qemu-guest-agent
      state: latest
      update_cache: true

  # - name: Start qemu-guest-agent
  #   ansible.builtin.systemd:
  #     name: qemu-guest-agent
  #     enabled: true
  #     state: started

  - name: Remove iscsi utilities
    ansible.builtin.apt:
      name: open-iscsi
      state: absent

  - name: NFS common utilities
    ansible.builtin.apt:
      name: nfs-common
      state: present

  - name: Update everything in APT
    ansible.builtin.apt:
      name: '*'
      state: latest

  - name: Remove useless packages from the cache
    ansible.builtin.apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    ansible.builtin.apt:
      autoremove: yes



# ---
#   - name: Is {{ hostname }} built?
#     ansible.builtin.shell: pvesh get /cluster/resources -type vm | grep {{ targetid }}
#     ignore_errors: true
#     register: built

#   - name: clone template to  {{ hostname }}
#     ansible.builtin.raw: qm clone {{ cloneid }} {{ targetid }} --name {{ hostname }}
#     when: built.rc != 0

#   - name: configure VM
#     ansible.builtin.raw: qm set {{ targetid }} --cores 2 --memory 2048

#   - name: config network
#     ansible.builtin.raw: qm set {{ targetid }} --ipconfig0 ip={{ ip }},gw=192.168.100.254
