---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: podinfo-http
  namespace: podinfo
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: kube-system
      sectionName: web
  hostnames:
    - test.3756home.org
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
    - backendRefs:
        - name: podinfo
          port: 9898
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: podinfo-https
#   namespace: podinfo
# spec:
#   parentRefs:
#     - name: cert-manager-gateway
#       namespace: cert-manager
#       sectionName: podinfo-https
#   # hostnames:
#   #   - test.3756home.org
#   rules:
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /
#     - backendRefs:
#         - name: podinfo
#           port: 9898
