apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: podinfo-route
spec:
  parentRefs:
    - name: cert-manager-gateway
      namespace: cert-manager
  hostnames:
    - test.3756home.org
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: my-release-podinfo
          port: 9898
