apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  description: CloudNativePG Cluster

  instances: 2

  postgresql:
    parameters:
      shared_buffers: "1024MB"

  resources:
    requests:
      memory: "1024Mi"
      cpu: 1

  storage:
    size: 2Gi