apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cert-manager-gateway
  namespace: cert-manager
  annotations:
    cert-manager.io/cluster-issuer: clusterissuer
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All

    - name: testcert
      hostname: test.3756home.org
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        # mode: Terminate
        certificateRefs:
          - name: test-3756home
