apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: cert-manager
  annotations:
    cert-manager.io/cluster-issuer: gateway-clusterissuer
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    
    allowedRoutes:
        namespaces:
          from: All

  - name: https-example
    hostname: example.3756home.org
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
        - name: https-examplehome-tls
